---
tablecloth:
    messaging:
        messagelength: 1024

---
grails:
    profile: web
    codegen:
        defaultPackage: tablecloth
    spring:
        transactionManagement:
            proxies: false
    gorm:
        failOnError: true
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

grails.plugin.springsecurity.password.algorithm: 'bcrypt'
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: admin
    password: ''

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:C:\tablecloth\devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:~\tablecloth\testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            pooled: true
            dbCreate: update
            driverClassName: "com.mysql.jdbc.Driver"
            username: 'admin'
            password: 'Dungeon123'
            url: "tablecloth-db.c2wnk7wolzew.eu-central-1.rds.amazonaws.com:3306/ebdb"
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            properties:
                validationQuery: "SELECT 1"
                testOnBorrow: true
                testOnReturn: true
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 1000 * 60 * 30
                numTestsPerEvictionRun: 3
                minEvictableIdleTimeMillis: 1000 * 60 * 30
